import { z } from 'zod';

// Define Gemini models enum
export const GeminiModelEnum = z.enum(['gemini-pro', 'gemini-ultra', 'gemini-nano', 'gemini-1.5-pro']);

export const PromptSchema = z.object({
  // UUID, optional because it's generated by DB if missing
  id: z.string().uuid().optional(),

  // Core Content
  promptText: z.string().min(10, "Prompt content too short"),
  systemInstruction: z.string().optional(),
  
  // Metadata
  title: z.string().min(5).max(100),
  tags: z.array(z.string()).default([]),
  
  // Source Info
  sourcePlatform: z.enum(['github', 'reddit', 'official_docs', 'web', 'social']),
  originUrl: z.string().url(),
  author: z.string().optional(),
  
  // Technical Specs
  modelTarget: z.string().optional(), // e.g., "gemini-1.5-pro"
  modality: z.array(z.string()).default(["text"]), // e.g., ["text", "image"]
  
  // Schemas
  inputSchema: z.record(z.string(), z.any()).optional(),
  outputSchema: z.record(z.string(), z.any()).optional(),
  
  // Context
  contextUrls: z.array(z.string().url()).optional(),
  
  // Metrics
  metaMetrics: z.object({
    upvotes: z.number().optional(),
    stars: z.number().optional(),
    forks: z.number().optional(),
  }).optional(),
  
  fetchedAt: z.string().datetime().optional(),
});

export type GeminiPrompt = z.infer<typeof PromptSchema>;
